$env:AWS_ACCESS_KEY_ID="REPLACE_WITH_ACCESS_KEY_ID"
$env:AWS_SECRET_ACCESS_KEY="REPLACE_WITH_SECRET_ACCESS_KEY"
$env:DOMAIN="REPLACE_WITH_DOMAIN.com"
$env:CLOUDFRONT_DISTRIBUTION_ID="REPLACE_WITH_DISTRIBUTION_ID"
